language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk7

env:
  - MAVEN_OPTS=-Dpython=python3
  - MAVEN_OPTS=-Dpython=python2

matrix:
  fast_finish: true

before_install:
  - python2 --version
  - python3 --version
  - pip install --user -r requirements.txt
